all: problem1 problem2 problem3

problem1: problem1.c problem1.o
	gcc -o problem1 problem1.c -pthread
	
problem2: problem2.c problem2.o
	gcc -o problem2 problem2.c -pthread
	
problem3: problem3.c problem3.o
	gcc -o problem3 problem3.c -pthread	
	
clean:
	rm -f *.o
	
